<?php

namespace AppBundle\Repository;

/**
 * CategoryResponseLevelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryResponseLevelsRepository extends \Doctrine\ORM\EntityRepository
{
}
