<?php

namespace AppBundle\Repository;

/**
 * QuestionCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
