<?php

namespace AppBundle\Repository;

/**
 * ResponseLevelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponseLevelsRepository extends \Doctrine\ORM\EntityRepository
{
}
