<?php

namespace AppBundle\Repository;

/**
 * response_weightageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class response_weightageRepository extends \Doctrine\ORM\EntityRepository
{
}
